# Generated by Django 2.2.5 on 2021-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='이름')),
                ('venue', models.CharField(max_length=200, verbose_name='주소')),
                ('category', models.CharField(max_length=200, verbose_name='카테고리')),
                ('tel', models.CharField(max_length=200, verbose_name='전화번호')),
                ('img_url', models.URLField(blank=True, max_length=400, verbose_name='썸네일 URL')),
            ],
        ),
    ]
