# Generated by Django 2.2.5 on 2021-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='PW')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='닉네임')),
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='프로필 사진')),
                ('species', models.CharField(max_length=20, null=True, verbose_name='반려동물 종')),
                ('local', models.CharField(max_length=20, null=True, verbose_name='지역(구/동)')),
            ],
        ),
    ]
