# Generated by Django 2.2.5 on 2021-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210216_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=20, null=True, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='아이디'),
        ),
    ]
