# Generated by Django 2.2.5 on 2021-02-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('pps_title', models.CharField(max_length=100, verbose_name='글 제목')),
                ('pps_contents', models.CharField(max_length=300, verbose_name='글 내용')),
                ('pps_date', models.DateTimeField(verbose_name='글 작성일')),
                ('pps_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Posthr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('phr_title', models.CharField(max_length=100, verbose_name='글 제목')),
                ('phr_contents', models.CharField(max_length=300, verbose_name='글 내용')),
                ('phr_date', models.DateTimeField(verbose_name='글 작성일')),
                ('phr_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('p_title', models.CharField(max_length=100, verbose_name='글 제목')),
                ('p_contents', models.CharField(max_length=300, verbose_name='글 내용')),
                ('p_date', models.DateTimeField(verbose_name='글 작성일')),
                ('p_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
